services:
  # --- Infrastructure ---
  tele-remote:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/tele-remote:${TAG:-latest}
    container_name: tele-remote
    restart: unless-stopped
    ports:
      - "${TR_IP:-127.0.0.1}:${TR_PORT:-1863}:${TR_PORT:-1863}"
    networks:
      - teleremote-network
    labels: [ com.centurylinklabs.watchtower.enable=true ]

networks:
  teleremote-network:
    name: teleremote-network
    external: true
