services:
  # --- Infrastructure ---
  tele-remote:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/tele-remote:${TAG:-latest}
    container_name: tele-remote
    restart: unless-stopped
    ports:
      - "127.0.0.2:${TR_PORT:-1863}:${TR_PORT:-1863}"
    networks:
      - teleremote_network
    labels: [ com.centurylinklabs.watchtower.enable=true ]

networks:
  teleremote_network:
    external: true
