// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: teleremote.proto

package grpc_control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotCommand_CommandType int32

const (
	BotCommand_UNKNOWN             BotCommand_CommandType = 0
	BotCommand_POWER_OFF           BotCommand_CommandType = 1
	BotCommand_CLOSE_ALL_POSITIONS BotCommand_CommandType = 2
	// Extendable for arbitrarily complex commands
	BotCommand_CUSTOM_COMMAND BotCommand_CommandType = 99
)

// Enum value maps for BotCommand_CommandType.
var (
	BotCommand_CommandType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "POWER_OFF",
		2:  "CLOSE_ALL_POSITIONS",
		99: "CUSTOM_COMMAND",
	}
	BotCommand_CommandType_value = map[string]int32{
		"UNKNOWN":             0,
		"POWER_OFF":           1,
		"CLOSE_ALL_POSITIONS": 2,
		"CUSTOM_COMMAND":      99,
	}
)

func (x BotCommand_CommandType) Enum() *BotCommand_CommandType {
	p := new(BotCommand_CommandType)
	*p = x
	return p
}

func (x BotCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_teleremote_proto_enumTypes[0].Descriptor()
}

func (BotCommand_CommandType) Type() protoreflect.EnumType {
	return &file_teleremote_proto_enumTypes[0]
}

func (x BotCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotCommand_CommandType.Descriptor instead.
func (BotCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_teleremote_proto_rawDescGZIP(), []int{3, 0}
}

// A message sent from the external component/service to the Bot
type ComponentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ComponentMessage_Registration
	//	*ComponentMessage_Telemetry
	//	*ComponentMessage_Qmsg
	Payload       isComponentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentMessage) Reset() {
	*x = ComponentMessage{}
	mi := &file_teleremote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMessage) ProtoMessage() {}

func (x *ComponentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_teleremote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMessage.ProtoReflect.Descriptor instead.
func (*ComponentMessage) Descriptor() ([]byte, []int) {
	return file_teleremote_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentMessage) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentMessage) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ComponentMessage) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ComponentMessage) GetPayload() isComponentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ComponentMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*ComponentMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *ComponentMessage) GetTelemetry() string {
	if x != nil {
		if x, ok := x.Payload.(*ComponentMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return ""
}

func (x *ComponentMessage) GetQmsg() *QueueMessage {
	if x != nil {
		if x, ok := x.Payload.(*ComponentMessage_Qmsg); ok {
			return x.Qmsg
		}
	}
	return nil
}

type isComponentMessage_Payload interface {
	isComponentMessage_Payload()
}

type ComponentMessage_Registration struct {
	// Initial registration message
	Registration *Registration `protobuf:"bytes,4,opt,name=registration,proto3,oneof"`
}

type ComponentMessage_Telemetry struct {
	// Data to forward to the telegram chat (e.g. logging)
	Telemetry string `protobuf:"bytes,5,opt,name=telemetry,proto3,oneof"`
}

type ComponentMessage_Qmsg struct {
	// A structured message (similar to legacy Qmsg)
	Qmsg *QueueMessage `protobuf:"bytes,6,opt,name=qmsg,proto3,oneof"`
}

func (*ComponentMessage_Registration) isComponentMessage_Payload() {}

func (*ComponentMessage_Telemetry) isComponentMessage_Payload() {}

func (*ComponentMessage_Qmsg) isComponentMessage_Payload() {}

type Registration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A JSON string representing a tree of menus and commands
	MenuJson      string `protobuf:"bytes,1,opt,name=menu_json,json=menuJson,proto3" json:"menu_json,omitempty"`
	SubType       string `protobuf:"bytes,2,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	PubConfig     string `protobuf:"bytes,3,opt,name=pub_config,json=pubConfig,proto3" json:"pub_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_teleremote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_teleremote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_teleremote_proto_rawDescGZIP(), []int{1}
}

func (x *Registration) GetMenuJson() string {
	if x != nil {
		return x.MenuJson
	}
	return ""
}

func (x *Registration) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *Registration) GetPubConfig() string {
	if x != nil {
		return x.PubConfig
	}
	return ""
}

type QueueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FromAddr      string                 `protobuf:"bytes,3,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	ToAddr        string                 `protobuf:"bytes,4,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	Ackw          *string                `protobuf:"bytes,5,opt,name=ackw,proto3,oneof" json:"ackw,omitempty"`
	Priority      bool                   `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_teleremote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_teleremote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_teleremote_proto_rawDescGZIP(), []int{2}
}

func (x *QueueMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueueMessage) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *QueueMessage) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *QueueMessage) GetAckw() string {
	if x != nil && x.Ackw != nil {
		return *x.Ackw
	}
	return ""
}

func (x *QueueMessage) GetPriority() bool {
	if x != nil {
		return x.Priority
	}
	return false
}

// A command sent from the Telegram Bot to the connected component(s)
type BotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   BotCommand_CommandType `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=teleremote.BotCommand_CommandType" json:"command_type,omitempty"`
	CustomPayload string                 `protobuf:"bytes,2,opt,name=custom_payload,json=customPayload,proto3" json:"custom_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotCommand) Reset() {
	*x = BotCommand{}
	mi := &file_teleremote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCommand) ProtoMessage() {}

func (x *BotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_teleremote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCommand.ProtoReflect.Descriptor instead.
func (*BotCommand) Descriptor() ([]byte, []int) {
	return file_teleremote_proto_rawDescGZIP(), []int{3}
}

func (x *BotCommand) GetCommandType() BotCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return BotCommand_UNKNOWN
}

func (x *BotCommand) GetCustomPayload() string {
	if x != nil {
		return x.CustomPayload
	}
	return ""
}

var File_teleremote_proto protoreflect.FileDescriptor

const file_teleremote_proto_rawDesc = "" +
	"\n" +
	"\x10teleremote.proto\x12\n" +
	"teleremote\"\xfc\x01\n" +
	"\x10ComponentMessage\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12>\n" +
	"\fregistration\x18\x04 \x01(\v2\x18.teleremote.RegistrationH\x00R\fregistration\x12\x1e\n" +
	"\ttelemetry\x18\x05 \x01(\tH\x00R\ttelemetry\x12.\n" +
	"\x04qmsg\x18\x06 \x01(\v2\x18.teleremote.QueueMessageH\x00R\x04qmsgB\t\n" +
	"\apayload\"e\n" +
	"\fRegistration\x12\x1b\n" +
	"\tmenu_json\x18\x01 \x01(\tR\bmenuJson\x12\x19\n" +
	"\bsub_type\x18\x02 \x01(\tR\asubType\x12\x1d\n" +
	"\n" +
	"pub_config\x18\x03 \x01(\tR\tpubConfig\"\xa4\x01\n" +
	"\fQueueMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tfrom_addr\x18\x03 \x01(\tR\bfromAddr\x12\x17\n" +
	"\ato_addr\x18\x04 \x01(\tR\x06toAddr\x12\x17\n" +
	"\x04ackw\x18\x05 \x01(\tH\x00R\x04ackw\x88\x01\x01\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\bR\bpriorityB\a\n" +
	"\x05_ackw\"\xd2\x01\n" +
	"\n" +
	"BotCommand\x12E\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2\".teleremote.BotCommand.CommandTypeR\vcommandType\x12%\n" +
	"\x0ecustom_payload\x18\x02 \x01(\tR\rcustomPayload\"V\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tPOWER_OFF\x10\x01\x12\x17\n" +
	"\x13CLOSE_ALL_POSITIONS\x10\x02\x12\x12\n" +
	"\x0eCUSTOM_COMMAND\x10c2X\n" +
	"\x11TeleRemoteService\x12C\n" +
	"\aConnect\x12\x1c.teleremote.ComponentMessage\x1a\x16.teleremote.BotCommand(\x010\x01B\x1eZ\x1ctele-remote/src/grpc_controlb\x06proto3"

var (
	file_teleremote_proto_rawDescOnce sync.Once
	file_teleremote_proto_rawDescData []byte
)

func file_teleremote_proto_rawDescGZIP() []byte {
	file_teleremote_proto_rawDescOnce.Do(func() {
		file_teleremote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teleremote_proto_rawDesc), len(file_teleremote_proto_rawDesc)))
	})
	return file_teleremote_proto_rawDescData
}

var file_teleremote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_teleremote_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_teleremote_proto_goTypes = []any{
	(BotCommand_CommandType)(0), // 0: teleremote.BotCommand.CommandType
	(*ComponentMessage)(nil),    // 1: teleremote.ComponentMessage
	(*Registration)(nil),        // 2: teleremote.Registration
	(*QueueMessage)(nil),        // 3: teleremote.QueueMessage
	(*BotCommand)(nil),          // 4: teleremote.BotCommand
}
var file_teleremote_proto_depIdxs = []int32{
	2, // 0: teleremote.ComponentMessage.registration:type_name -> teleremote.Registration
	3, // 1: teleremote.ComponentMessage.qmsg:type_name -> teleremote.QueueMessage
	0, // 2: teleremote.BotCommand.command_type:type_name -> teleremote.BotCommand.CommandType
	1, // 3: teleremote.TeleRemoteService.Connect:input_type -> teleremote.ComponentMessage
	4, // 4: teleremote.TeleRemoteService.Connect:output_type -> teleremote.BotCommand
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_teleremote_proto_init() }
func file_teleremote_proto_init() {
	if File_teleremote_proto != nil {
		return
	}
	file_teleremote_proto_msgTypes[0].OneofWrappers = []any{
		(*ComponentMessage_Registration)(nil),
		(*ComponentMessage_Telemetry)(nil),
		(*ComponentMessage_Qmsg)(nil),
	}
	file_teleremote_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teleremote_proto_rawDesc), len(file_teleremote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teleremote_proto_goTypes,
		DependencyIndexes: file_teleremote_proto_depIdxs,
		EnumInfos:         file_teleremote_proto_enumTypes,
		MessageInfos:      file_teleremote_proto_msgTypes,
	}.Build()
	File_teleremote_proto = out.File
	file_teleremote_proto_goTypes = nil
	file_teleremote_proto_depIdxs = nil
}
