// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: teleremote.proto

package grpc_control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeleRemoteService_Connect_FullMethodName = "/teleremote.TeleRemoteService/Connect"
)

// TeleRemoteServiceClient is the client API for TeleRemoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeleRemoteServiceClient interface {
	// Bi-directional stream for connecting a component to the bot gateway
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ComponentMessage, BotCommand], error)
}

type teleRemoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeleRemoteServiceClient(cc grpc.ClientConnInterface) TeleRemoteServiceClient {
	return &teleRemoteServiceClient{cc}
}

func (c *teleRemoteServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ComponentMessage, BotCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeleRemoteService_ServiceDesc.Streams[0], TeleRemoteService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComponentMessage, BotCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeleRemoteService_ConnectClient = grpc.BidiStreamingClient[ComponentMessage, BotCommand]

// TeleRemoteServiceServer is the server API for TeleRemoteService service.
// All implementations must embed UnimplementedTeleRemoteServiceServer
// for forward compatibility.
type TeleRemoteServiceServer interface {
	// Bi-directional stream for connecting a component to the bot gateway
	Connect(grpc.BidiStreamingServer[ComponentMessage, BotCommand]) error
	mustEmbedUnimplementedTeleRemoteServiceServer()
}

// UnimplementedTeleRemoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeleRemoteServiceServer struct{}

func (UnimplementedTeleRemoteServiceServer) Connect(grpc.BidiStreamingServer[ComponentMessage, BotCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedTeleRemoteServiceServer) mustEmbedUnimplementedTeleRemoteServiceServer() {}
func (UnimplementedTeleRemoteServiceServer) testEmbeddedByValue()                           {}

// UnsafeTeleRemoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeleRemoteServiceServer will
// result in compilation errors.
type UnsafeTeleRemoteServiceServer interface {
	mustEmbedUnimplementedTeleRemoteServiceServer()
}

func RegisterTeleRemoteServiceServer(s grpc.ServiceRegistrar, srv TeleRemoteServiceServer) {
	// If the following call panics, it indicates UnimplementedTeleRemoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeleRemoteService_ServiceDesc, srv)
}

func _TeleRemoteService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeleRemoteServiceServer).Connect(&grpc.GenericServerStream[ComponentMessage, BotCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeleRemoteService_ConnectServer = grpc.BidiStreamingServer[ComponentMessage, BotCommand]

// TeleRemoteService_ServiceDesc is the grpc.ServiceDesc for TeleRemoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeleRemoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teleremote.TeleRemoteService",
	HandlerType: (*TeleRemoteServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _TeleRemoteService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "teleremote.proto",
}
