# [FLEET-ARCHITECT] Microservice (Go:1.25, Py:3.12, Rust:1.91, C++:20)
name: Fleet CI
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  fleet-ci:
    uses: Bastien-Antigravity/fleet-operation-brain/.github/workflows/master-ci.yml@develop
    secrets: inherit
